- name: database execution query
  hosts: db
  become: yes
  tasks: 
  - name: install MYSQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: import mysql data
    community.mysql.mysql_query:
      login_db: mysql
      login_host: mysql.learndevopsacademy.online
      login_user: root
      login_password: ExpenseApp@1
      query: insert into transactions (id,amount,description) values (1002,50,'lunch')