- name: Execute a database query using MySQL client
  hosts: db
  become: true  # If the user requires elevated privileges
  tasks:
  - name: install MYSQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: Execute SQL query
    shell: >
        mysql --defaults-extra-file=/root/.my.cnf -e "use transactions; SELECT * FROM transactions;"
    register: query_result

  - name: Format query result
    copy:
      content: |
          Query Results:
          
          {{ query_result.stdout | regex_replace('\t', '  ') }}
    dest: /tmp/query_results.txt