- name: database execution query
  hosts: db
  become: yes
  tasks: 
  - name: import mysql data
    community.mysql.mysql_query:
      login_db: mysql
      login_host: mysql.learndevopsacademy.online
      login_user: root
      login_password: ExpenseApp@1
      query: select Host,User from user